project:
  type: book

book:
  title: "Programlama-temeller"
  author: "Atilla Özgür"
  date: today
  date-format: "YYYY-MM-DD"
  cover-image: cover.png
  chapters:  
    - index.qmd
    - part: "Giriş"
      chapters:  
        - bolumler/giris/giris.qmd
        - bolumler/yazilim-gelistirme-yasam-dongusu/yazilim-gelistirme-yasam-dongusu.qmd
        - bolumler/program-tasarim/program-tasarim.qmd
        - bolumler/sahte-kod/sahte-kod.qmd
        - bolumler/akis-cizimleri/akis-cizimleri.qmd
        - bolumler/merhaba-dunya/merhaba-dunya.qmd
        - bolumler/cevrimici-kod-yazma/cevrimici-kod-yazma.qmd
        - bolumler/kurulum/kurulum.qmd
        - bolumler/komut-satiri/komut-satiri.qmd
        - bolumler/programcinin-metin-duzenleyicisi/programcinin-metin-duzenleyicisi.qmd
        - bolumler/girdi-cikti/girdi-cikti.qmd
        - bolumler/hata-ayiklama/hata-ayiklama.qmd
        - bolumler/butunlesik-gelistirme-ortami/butunlesik-gelistirme-ortami.qmd        
        - bolumler/sabitler-ve-degiskenler/sabitler-ve-degiskenler.qmd
        - bolumler/lab-uzaktan-kumanda/uzaktan-kumanda-dotnet1.qmd
    - references.qmd



filters:
  - pseudocode
  - include-code-files  

link-citations: true


format:
  html:
    theme: cosmo
    code-line-numbers: true    
    code-fold: false
    code-tools: false
    include-in-header:
      text: |
        <script>
        MathJax = {
          loader: {
            load: ['[tex]/boldsymbol']
          },
          tex: {
            tags: "all",
            inlineMath: [['$','$'], ['\\(','\\)']],
            displayMath: [['$$','$$'], ['\\[','\\]']],
            processEscapes: true,
            processEnvironments: true,
            packages: {
              '[+]': ['boldsymbol']
            }
          }
        };
        </script>
        <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
  pdf:
    documentclass: scrreprt
    include-in-header:
      text: |
        \usepackage{xeCJK}
    include-before-body:
      text: |
        \renewcommand{\Return}{\State \textbf{return}~}
        \newcommand{\Print}{\State \textbf{print}~}
        \newcommand{\Break}{\State \textbf{break}}
        \newcommand{\Continue}{\State \textbf{continue}}
        \newcommand{\True}{\textbf{true}}
        \newcommand{\False}{\textbf{false}}
        \renewcommand{\And}{\textbf{and}~}
        \newcommand{\Or}{\textbf{or}~}
        \renewcommand{\Not}{\textbf{not}~}
        \newcommand{\To}{\textbf{to}~}
        \newcommand{\DownTo}{\textbf{downto}~}
        \numberwithin{algorithm}{chapter}
    pdf-engine: xelatex
    toc-depth: 2

bibliography: references.bib
csl: ieee.csl
callout-appearance: simple
