project:
  type: book

book:
  title: "Programlama-temeller"
  author: "Atilla Özgür"
  date: today
  date-format: "YYYY-MM-DD"
  cover-image: cover.png
  chapters:
    - index.qmd
    - intro.qmd
    - yazilim-gelistirme-yasam-dongusu.qmd
    - program-tasarım.qmd
    - sahte-kod.qmd
    - akis-diagramlari.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib
csl: ieee.csl
callout-appearance: simple

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



