project:
  type: book

book:
  title: "Programlama-temeller"
  author: "Atilla Özgür"
  date: today
  date-format: "YYYY-MM-DD"
  cover-image: cover.png
  chapters:  
    - index.qmd
    - part: "Giriş"
      chapters:  
        - bolumler/giris/giris.qmd
        - bolumler/yazilim-gelistirme-yasam-dongusu/yazilim-gelistirme-yasam-dongusu.qmd
        - bolumler/program-tasarim/program-tasarim.qmd
        - bolumler/sahte-kod/sahte-kod.qmd
        - bolumler/akis-diagramlari/akis-diagramlari.qmd
        - bolumler/merhaba-dunya/merhaba-dunya.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib
csl: ieee.csl
callout-appearance: simple

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



