```{mermaid}
flowchart LR
    title[Şelale Yazılım Geliştirme Yaşam Döngüsü]
    
    S(Sistem Gereksinimleri) 
    S --> Y(Yazılım Gereksinimleri)
    Y --> A(Analiz)
    A --> D(Tasarım)
    D --> C(Kodlama)
    C --> T(Test)
    T --> O(Operasyon)
    O --> S
 ```


