```{mermaid}
flowchart LR
    S(System Requirements) 
    S --> R(Software Requirements)
    R --> S
    R --> A(Analysis)
    A --> D(Design)
    D --> C(Coding)
    C --> T(Testing)
    T --> O(Operations)
    O --> S
 ```


