```{mermaid}
flowchart LR
    title[Değiştirilmiş Şelale Yazılım Geliştirme Yaşam Döngüsü]

    S(System Requirements) 
    S --> R(Software Requirements)
    R --> S 
    R --> A(Analysis)
    A --> R
    A --> D(Design)
    D --> A
    D --> C(Coding)
    C --> D
    C --> T(Testing)
    T --> C
    T --> O(Operations)
    O --> T
    O --> R
```


