# Yazılım Geliştirme Yaşam Döngüsü

Yazılım veya Sistem Geliştirme Yaşam Döngüsü, bir sistemin başlangıçtan son aşamasına kadar olan ara süreçleri tanımlar.
İlk önerilen şelale sisteminden sonra bir çok farklı yaşam döngüsü önerilmiştir.
Bunlar arasında aşağıdakiler sayılabilir.

- Şelale
- sarmal
- çevik yazılım geliştirme
- hızlı prototip oluşturma


Küçük yazılımlar aşağıdaki iki adımdan oluşur.
Bu kitapta çözeceğimiz tüm sorular ve herhangi bir derste öğreneceğiniz yazılımlar aşağıdaki iki adım yani analiz ve kodlama kullanarak çözülebilir.
Burada analiz parçası problemin incelenmesi, kodlama bu inceleme sonrasında yazılan kodu içermektedir.


{{< include ./diagramlar/analiz-kodlama.mmd >}}


Ama yazılım projeleri büyüdükçe daha tutarlı ve resmi bir döngü takip edilmesi gerekir.
Bu döngülerden şelale aşağıdaki diagramda verilmiştir.



{{< include ./diagramlar/waterfall.mmd >}}

Bu diagram'a şelale ismi daha sonradan verilmiştir.
Bu diagram üzerinde geri dönüşler olmadığı için şelale ismi kullanılmaktadır ama bu döngüyü ile öneren makalede @Royce1987Managing bile, geri dönüşler vardır.
Yani test sırasında bir hata olduğu görüldüğü zaman, daha önceki adımlara dönülmektedir.
Bu diagram aşağıda görülebilir.

{{< include ./diagramlar/waterfall-real.mmd >}}


Şelale döngüsündeki adımlar aşağıdaki gibidir.


- Sistem gereksinimleri: Yazılımın çalışacağı işletim sistemi, donanım gibi diğer gereksinimlerin tanımlanması. Örneğin bir savunma sanayi yazılımında bu gereksinimler çok daha önemlidir. Bir oyun için örneğin mobil veya masaüstü desteği burada karar verilmelidir.

- Yazılım gereksinimleri: Sistem gereksinimlerine göre yazılımın gereksinimlerinin yazılması

- Analiz: Daha önceki iki sistem ve yazılım gereksinimlerinin incelenmesi ve doğrulanması adımdır.

Bu ilk üç adım bazı yerlerde gereksinim analizi olarak aşağıdaki gibi birleştirilir.


{{< include ./diagramlar/waterfall1.mmd >}}

- Tasarım: Yazılımın veri tabanı tasarımı, ekran tasarımları, girdi-çıktı tasarımlarının yapıldığı adımdır.

- Kodlama: tasarım ve gereksinimleri göre yazılan kod yazılması adımıdır.

- Test: Yazılan kodun gereksinimleri karşılayıp karşılamadığının kontrol edildiği adımdır.

- Operasyon: Yazılımın son kullanıcı veya müşteriye ulaştırıldığı adımdır. Bu adım ayrıca bakım olarak ta adlandırılır.






