```{mermaid}
---
title : Yazılım Geliştirme Yaşam Döngüsü
---
flowchart LR
    S(Gereksinim Analizi) 
    S --> D(Tasarım)
    D --> C(Kodlama)
    C --> T(Test)
    T --> O(Operasyon)
    O --> S
 ```


